config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#top'
  resources :books, only:[:show, :create, :edit, :update, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :title, presence: true
validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top    
  end

  def index
    #全件取得
      @books = Book.all
      @book = Book.new

  end

  def show
    #指定したファイルを見つける
      @book = Book.find(params[:id])
  end

  def create
      @book = Book.new(book_params)
      #保存が成功した場合
      if @book.save
        flash[:notice] = 'Book was successfully created.'
         redirect_to @book
      #入力が正しくない場合
      else
         # redirect_to books_path
         @books = Book.all
         render :index
      end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
       @book = Book.find(params[:id])
      if @book.update(book_params)
         flash[:notice] = "Book was successfully updated"
         render 'show'
      else
         render 'edit'
      end
    
  end

  def destroy
      book = Book.find(params[:id])
      if book.destroy
         redirect_to books_path
      else
         redirect_to books_path
      end
  end

  private
  def book_params
      params.require(:book).permit(:title, :body)    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div>
    <ul style="color: red">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>

<% end %>
<!-- show -->
<%= link_to 'Show', book_path %>
<!-- back -->
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h2>Books</h2>
  <table>
  	<thead>
    <tr>
  	<th>Title</th>
  	<th>Body</th>
    </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
      <%= link_to "show", book_path(book.id) %>
      <%= link_to "edit", edit_book_path(book.id) %>
      <%= link_to "destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>

<h3>New book</h3>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <%= form_for(@book) do |f| %>
    <h4 class="title">本のタイトル</h4>
    <%= f.text_field :title %>
    <h4 class="body">本の感想</h4>
    <%= f.text_area :body %>  
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>


    <p>
  	  <strong>Title:</strong>
  	  	<%= @book.title %>
    </p>
    <p>
    	<strong>Body:</strong>
  	  <%= @book.body %>
    </p>
 <%= link_to "edit", edit_book_path(@book.id) %>
 <%= link_to "back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ
<strong>Bookers</strong>へ！
</h1>

<p>
<strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>